name: uni_deep_learning
channels:
  - pytorch
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - certifi=2025.10.5
  - cffi=1.17.1
  - charset-normalizer=3.4.3
  - click=8.3.0
  - colorama=0.4.6
  - contourpy=1.3.2
  - cpuonly=2.0
  - cpython=3.10.18
  - cycler=0.12.1
  - expat=2.7.1
  - filelock=3.20.0
  - fonttools=4.60.1
  - freetype=2.14.1
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - jinja2=3.1.6
  - kiwisolver=1.4.9
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libdeflate=1.22
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libsqlite=3.50.4
  - libtiff=4.7.0
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - mdurl=0.1.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.5
  - networkx=3.4.2
  - numpy=2.2.6
  - openjpeg=2.5.3
  - openssl=3.5.4
  - packaging=25.0
  - pillow=11.3.0
  - pip=25.2
  - pthread-stubs=0.4
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - python=3.10.15
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pytorch=2.5.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.3
  - qhull=2020.2
  - readline=8.3
  - requests=2.32.5
  - rich=14.2.0
  - setuptools=80.9.0
  - shellingham=1.5.4
  - six=1.17.0
  - sqlite=3.50.2
  - sympy=1.14.0
  - tk=8.6.15
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tornado=6.5.2
  - tqdm=4.67.1
  - typer=0.19.2
  - typer-slim=0.19.2
  - typer-slim-standard=0.19.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - urllib3=2.5.0
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
